name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-cli:
    name: publish cargo-oneway to crates.io
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: cli
      - run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
